"""empty message

Revision ID: 5f93faa0fe1e
Revises: 
Create Date: 2022-06-15 15:34:27.196805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f93faa0fe1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='课程名称'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='姓名'),
    sa.Column('sex', sa.Boolean(), nullable=True, comment='性别'),
    sa.Column('class_number', sa.String(length=32), nullable=True, comment='班级'),
    sa.Column('age', sa.SmallInteger(), nullable=True, comment='年龄'),
    sa.Column('description', sa.Text(), nullable=True, comment='个性签名'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_class_number'), 'student', ['class_number'], unique=False)
    op.create_index(op.f('ix_student_name'), 'student', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_name'), table_name='student')
    op.drop_index(op.f('ix_student_class_number'), table_name='student')
    op.drop_table('student')
    op.drop_table('course')
    # ### end Alembic commands ###
